version: "3.6"
services:
# Redis Governace
  redis:
    image: redis
    hostname: redis
    command: redis-server --requirepass redis --port 6377

# Auth Governace
  auth:
    image: polkassembly-auth
    build:
      context: ../auth-server
      dockerfile: Dockerfile
    restart: always
    depends_on:
      - "redis"
    ports:
      - "8010:8010"
    environment:
      REDIS_URL: "redis://:redis@redis:6377"
      REACT_APP_AUTH_URL: "http://localhost:8010"
      REACT_APP_SERVER_URL: "http://localhost:8080/v1/graphql"
      NODE_ENV: ${NODE_ENV}
      DOMAIN_PROTOCOL: ${DOMAIN_PROTOCOL}
      DATABASE_URL: ${DATABASE_URL}
      SENDGRID_API_KEY: ${SENDGRID_API_KEY}
      PORT: ${PORT}
      PROPOSAL_BOT_USER_ID: ${PROPOSAL_BOT_USER_ID}
      EVENT_BOT_USER_ID: ${EVENT_BOT_USER_ID}
      DOMAIN_NAME: ${DOMAIN_NAME}
      JWT_KEY_PASSPHRASE: ${JWT_KEY_PASSPHRASE}
      HASURA_EVENT_SECRET: ${HASURA_GRAPHQL_ADMIN_SECRET}
      # Intentionally checking in private key for running transient docker container.
      # This private key is only used here and nowhere else.
      JWT_PUBLIC_KEY: ${JWT_PUBLIC_KEY}
      JWT_PRIVATE_KEY: ${JWT_PRIVATE_KEY}


